### ISSUE TITLE
Feature Request - add a section in the readme that explain how to run this little web site

### ISSUE THREAD

**Issue by oren** [asalazar2127/word-of-the-week#2]
``` js
// core node module
var http = require('http');


// every http request will enter this function
var handler = function (req, res) {
  console.log('request coming');

  var word = random();
  res.setHeader('Content-Type', 'text/html');
  res.end('<h2> wow </h2> <p>' + word  + '</p>');
};

var words = ['aoue', 'wow'];

function random() {
  // var index = find number between 0 - 9 
  var index = 1;
  return words[index];
}

var server = http.createServer(handler)
```

**Comment by oren** [comment]
@pquinal and @Tewt : the above code is a tiny website that display `<h2> wow </h2> <p> wow </p>`
I wrote it with @asalazar2127 tonight and It will be cool if he will write a step by step instructions for you guys to run it on your laptops and also answer questions you have.

**Comment by oren** [comment]
we forgot one line. our server must listen on some port - `server.listen(3000);`

**Comment by asalazar2127** [comment]
To run outside the container:
window type "boot2docker ip"
copy that ip address and put that in your terminal
and then :3000
then enter "docker-compose run --service-ports app node src/server.js" in the terminal 
To run inside the container:
once inside container enter "docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)"
then "docker-compose run --service-ports app node src/server.js"

**Comment by oren** [comment]
Sweet!
